### PR TITLE
Use develop as main dev branch

### PR DESCRIPTION
**Pull request by aiham**
Merging master into develop

### CODE REVIEW

**Comment by wanderingstan** [comment]
Thanks @aiham ! 

Any tips on how to message people in the future that they should be making PR's to `develop` and not `master`?

**Comment by aiham** [comment]
@wanderingstan from https://stackoverflow.com/a/14858326

> make develop the default branch that everyone sees when visiting the project. The downside is that anyone who clones it will get an unstable branch by default but all pull requests will go to the develop branch by default too.

**Comment by aiham** [comment]
Alternatively you could flip it and use `master` and `stable` where all dev happens on master

**Comment by aiham** [comment]
I think either way you'll need the default branch to be unstable to receive PRs to it automatically

**Pull request merged**
